PAYLOAD_EVENT_ARG = "Payload"
SNAPSHOT_DATE_EVENT_ARG = "snapshot_date"
FORMAT_ID_EVENT_ARG = "format_id"
REPLAY_LIST_EVENT_ARG = "replay_list"
REPLAY_ID_EVENT_ARG = "id"
REPLAY_USERNAME_EVENT_ARG = "username"
REPLAY_RATING_EVENT_ARG = "rating"
REPLAY_FORMAT_EVENT_ARG = "format"
REPLAY_LOG_EVENT_ARG = "log"
REPLAY_UPLOAD_DATE_EVENT_ARG = "upload_date"

TEAM_SIZE = 6
